Only link to non broken links on First Mark page
mysociety/ceuk-marking pull request #162
Opened 2024-06-11 16:04 UTC by struan

Uses the list of link status codes provided by CEUK to generate a list of bad links and then uses that to only turn good URLs into links in the previous responses part of the first mark page.

Fixes #146

2024-06-14 16:37 UTC, zarino requested changes
Code looks good, although I’ve not tried it end-to-end locally.

I wonder whether just printing out the broken URL will make it obvious enough that the link is actually broken? Should we include "[dead link]" after it?

I’d also be tempted to make dead links look _more_ prominent too. The aim of #146 (although I realise I didn’t document this at the time) was to _warn_ markers when a link has died, because that might mean the evidence that got a council a mark in the previous year _no longer exists_. Giving the link (or `<span>` if you still want it to just be plain text) a `class="text-danger"` attribute might help.

2024-06-17 13:43 UTC, zarino approved these changes
One typo! Aside from that, looks good.

2024-06-17 13:43 UTC, zarino commented on crowdsourcer/templatetags/neighbourhood_filters.py
> +        return mark_safe(f'<span class="text-danger">{text}</a>')
Should be `</span>` not `</a>`

2024-06-19 11:14 UTC, struan commented
Merges in 723ac35556a192b86473bfdb8e82801221828cc1

2024-06-19 11:14 UTC, closed without merging